name: Only dockerfiles

on:
  push:
  workflow_dispatch:

jobs:
  lint-dockerfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install hadolint
        run: |
          curl -fL -o hadolint https://github.com/hadolint/hadolint/releases/download/v1.19.0/hadolint-Linux-x86_64
          chmod +x hadolint
          sudo mv hadolint /usr/local/bin
      - name: Lint Dockerfiles
        run: |
          hadolint -f json docker-compose.yml | jq -c '.[] | .file + ":" + (.line|tostring) + " [DL" + .code + "] " + .message'