name: Only dockerfiles

on:
  push:
  workflow_dispatch:

jobs:
  lint-dockerfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install hadolint
        run: |
          curl -fL -o hadolint https://github.com/hadolint/hadolint/releases/download/v1.19.0/hadolint-Linux-x86_64
          chmod +x hadolint
          sudo mv hadolint /usr/local/bin

      - name: Extract Dockerfile paths from docker-compose.yml
        run: |
          DOCKERFILES=$(grep -oP '^\s*build:\s*\K.*Dockerfile$' docker-compose.yml)
          echo "Found Dockerfiles: $DOCKERFILES"
      - name: Lint Dockerfiles
        run: |
          for DOCKERFILE in $DOCKERFILES; do
            echo "Linting $DOCKERFILE"
            hadolint -f json "$DOCKERFILE" | jq -c '.[] | .file + ":" + (.line|tostring) + " [DL" + .code + "] " + .message'
          done
        env:
          HADOLINT_ERROR: "true"
      - name: Fail action on error
        if: env.HADOLINT_ERROR == "true"
        run: exit 1