name: Only dockerfiles

on: [push]

jobs:
  lint-dockerfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install hadolint
        run: |
          wget -O hadolint "https://github.com/hadolint/hadolint/releases/download/v1.18.3/hadolint-$(uname -s)-$(uname -m)"
          chmod +x hadolint
          sudo mv hadolint /usr/local/bin/
      - name: Lint Dockerfiles
        run: |
          hadolint -f json docker-compose.yml | jq -c '.[] | .file + ":" + (.line|tostring) + " [DL" + .code + "] " + .message'