name: trivy scans images built from a docker-compose file

on:
  [push, pull_request, workflow_dispatch]

env: 
  image_refs: ''

jobs:
  build-and-get-name:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/docker-compose 
    outputs:
      image_names: ${{ steps.get_names.outputs.image_names }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build docker image
        # working-directory: ./examples/docker-compose 
        run:
          docker compose build
      - name: Get Docker image names
        id: get_names
        run: |
          echo "Docker images to scan: "
          if [ -z $image_refs ]; then
          #   docker compose convert --images | tee image_names.txt
          # else
          #   echo $image_ref | tr ';' '\n' | tee image_names.txt 
            # echo image_names=($(echo $(docker compose convert --images) | tr '\n' ' ')) | tee $GITHUB_OUTPUT
            image_names_yq=$(docker compose convert --images)
            echo $image_names_yq
            image_names=($(echo $image_names_yq | tr '\n' ' '))
            echo "image_names: ${image_names[*]}"
            # echo image_names=${image_names[*]} >> $GITHUB_OUTPUT
            echo image_names="{\"image:\":[\"docker-compose-web\", \"docker-compose-db\"]}"  >> $GITHUB_OUTPUT
          fi

  trivy-scan:
    needs: build-and-get-name
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.build-and-get-name.outputs.image_names) }}
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ matrix.image }}
          exit-code: 0
          ignore-unfixed: true
          vuln-type: 'os,library'
          format: table
          severity: 'CRITICAL,HIGH'