name: trivy scans images built from a docker-compose file

on:
  [push, pull_request, workflow_dispatch]

env: 
  image_names: ''

jobs:
  build-and-get-name:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/docker-compose 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build docker image
        # working-directory: ./examples/docker-compose 
        run:
          docker compose build
      - name: Get Docker image names
        run: |
          echo "Docker images to scan: "
          if [ -z $image_names ]; then
          #   docker compose convert --images | tee image_names.txt
          # else
          #   echo $image_ref | tr ';' '\n' | tee image_names.txt 
            image_names=$(docker compose convert --images)
          fi

  trivy-scan:
    strategy:
      fail-fast: false
      matrix:
        image: env.image_names
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ matrix.image }}
          exit-code: 0
          ignore-unfixed: true
          vuln-type: 'os,library'
          format: table
          severity: 'CRITICAL,HIGH'